const countryCapitalData = {
  "africa": [
    { "country": "Algeria", "capital": "Algiers" },
    { "country": "Angola", "capital": "Luanda" },
    { "country": "Benin", "capital": "Porto-Novo" },
    { "country": "Botswana", "capital": "Gaborone" },
    { "country": "Burkina Faso", "capital": "Ouagadougou" },
    { "country": "Burundi", "capital": "Gitega" },
    { "country": "Cabo Verde", "capital": "Praia" },
    { "country": "Cameroon", "capital": "Yaoundé" },
    { "country": "Central African Republic", "capital": "Bangui" },
    { "country": "Chad", "capital": "N'Djamena" },
    { "country": "Comoros", "capital": "Moroni" },
    { "country": "Democratic Republic of the Congo", "capital": "Kinshasa" },
    { "country": "Republic of the Congo", "capital": "Brazzaville" },
    { "country": "Côte d'Ivoire", "capital": "Yamoussoukro" },
    { "country": "Djibouti", "capital": "Djibouti" },
    { "country": "Egypt", "capital": "Cairo" },
    { "country": "Equatorial Guinea", "capital": "Malabo" },
    { "country": "Eritrea", "capital": "Asmara" },
    { "country": "Eswatini", "capital": "Mbabane" },
    { "country": "Ethiopia", "capital": "Addis Ababa" },
    { "country": "Gabon", "capital": "Libreville" },
    { "country": "Gambia", "capital": "Banjul" },
    { "country": "Ghana", "capital": "Accra" },
    { "country": "Guinea", "capital": "Conakry" },
    { "country": "Guinea-Bissau", "capital": "Bissau" },
    { "country": "Kenya", "capital": "Nairobi" },
    { "country": "Lesotho", "capital": "Maseru" },
    { "country": "Liberia", "capital": "Monrovia" },
    { "country": "Libya", "capital": "Tripoli" },
    { "country": "Madagascar", "capital": "Antananarivo" },
    { "country": "Malawi", "capital": "Lilongwe" },
    { "country": "Mali", "capital": "Bamako" },
    { "country": "Mauritania", "capital": "Nouakchott" },
    { "country": "Mauritius", "capital": "Port Louis" },
    { "country": "Morocco", "capital": "Rabat" },
    { "country": "Mozambique", "capital": "Maputo" },
    { "country": "Namibia", "capital": "Windhoek" },
    { "country": "Niger", "capital": "Niamey" },
    { "country": "Nigeria", "capital": "Abuja" },
    { "country": "Rwanda", "capital": "Kigali" },
    { "country": "São Tomé and Príncipe", "capital": "São Tomé" },
    { "country": "Senegal", "capital": "Dakar" },
    { "country": "Seychelles", "capital": "Victoria" },
    { "country": "Sierra Leone", "capital": "Freetown" },
    { "country": "Somalia", "capital": "Mogadishu" },
    { "country": "South Africa", "capital": "Cape Town" },
    { "country": "South Sudan", "capital": "Juba" },
    { "country": "Sudan", "capital": "Khartoum" },
    { "country": "Tanzania", "capital": "Dodoma" },
    { "country": "Togo", "capital": "Lomé" },
    { "country": "Tunisia", "capital": "Tunis" },
    { "country": "Uganda", "capital": "Kampala" },
    { "country": "Zambia", "capital": "Lusaka" },
    { "country": "Zimbabwe", "capital": "Harare" }
  ],
  "asia": [
    { "country": "Afghanistan", "capital": "Kabul" },
    { "country": "Armenia", "capital": "Yerevan" },
    { "country": "Azerbaijan", "capital": "Baku" },
    { "country": "Bahrain", "capital": "Manama" },
    { "country": "Bangladesh", "capital": "Dhaka" },
    { "country": "Bhutan", "capital": "Thimphu" },
    { "country": "Brunei", "capital": "Bandar Seri Begawan" },
    { "country": "Cambodia", "capital": "Phnom Penh" },
    { "country": "China", "capital": "Beijing" },
    { "country": "Cyprus", "capital": "Nicosia" },
    { "country": "Georgia", "capital": "Tbilisi" },
    { "country": "India", "capital": "New Delhi" },
    { "country": "Indonesia", "capital": "Jakarta" },
    { "country": "Iran", "capital": "Tehran" },
    { "country": "Iraq", "capital": "Baghdad" },
    { "country": "Israel", "capital": "Jerusalem" },
    { "country": "Japan", "capital": "Tokyo" },
    { "country": "Jordan", "capital": "Amman" },
    { "country": "Kazakhstan", "capital": "Nur-Sultan" },
    { "country": "Kuwait", "capital": "Kuwait City" },
    { "country": "Kyrgyzstan", "capital": "Bishkek" },
    { "country": "Laos", "capital": "Vientiane" },
    { "country": "Lebanon", "capital": "Beirut" },
    { "country": "Malaysia", "capital": "Kuala Lumpur" },
    { "country": "Maldives", "capital": "Malé" },
    { "country": "Mongolia", "capital": "Ulaanbaatar" },
    { "country": "Myanmar", "capital": "Naypyidaw" },
    { "country": "Nepal", "capital": "Kathmandu" },
    { "country": "North Korea", "capital": "Pyongyang" },
    { "country": "Oman", "capital": "Muscat" },
    { "country": "Pakistan", "capital": "Islamabad" },
    { "country": "Palestine", "capital": "East Jerusalem" },
    { "country": "Philippines", "capital": "Manila" },
    { "country": "Qatar", "capital": "Doha" },
    { "country": "Russia", "capital": "Moscow" },
    { "country": "Saudi Arabia", "capital": "Riyadh" },
    { "country": "Singapore", "capital": "Singapore" },
    { "country": "South Korea", "capital": "Seoul" },
    { "country": "Sri Lanka", "capital": "Sri Jayawardenepura Kotte" },
    { "country": "Syria", "capital": "Damascus" },
    { "country": "Taiwan", "capital": "Taipei" },
    { "country": "Tajikistan", "capital": "Dushanbe" },
    { "country": "Thailand", "capital": "Bangkok" },
    { "country": "Timor-Leste", "capital": "Dili" },
    { "country": "Turkey", "capital": "Ankara" },
    { "country": "Turkmenistan", "capital": "Ashgabat" },
    { "country": "United Arab Emirates", "capital": "Abu Dhabi" },
    { "country": "Uzbekistan", "capital": "Tashkent" },
    { "country": "Vietnam", "capital": "Hanoi" },
    { "country": "Yemen", "capital": "Sana'a" }
  ],
  "europe": [
    { "country": "Albania", "capital": "Tirana" },
    { "country": "Andorra", "capital": "Andorra la Vella" },
    { "country": "Austria", "capital": "Vienna" },
    { "country": "Belarus", "capital": "Minsk" },
    { "country": "Belgium", "capital": "Brussels" },
    { "country": "Bosnia and Herzegovina", "capital": "Sarajevo" },
    { "country": "Bulgaria", "capital": "Sofia" },
    { "country": "Croatia", "capital": "Zagreb" },
    { "country": "Czech Republic", "capital": "Prague" },
    { "country": "Denmark", "capital": "Copenhagen" },
    { "country": "Estonia", "capital": "Tallinn" },
    { "country": "Finland", "capital": "Helsinki" },
    { "country": "France", "capital": "Paris" },
    { "country": "Germany", "capital": "Berlin" },
    { "country": "Greece", "capital": "Athens" },
    { "country": "Hungary", "capital": "Budapest" },
    { "country": "Iceland", "capital": "Reykjavik" },
    { "country": "Ireland", "capital": "Dublin" },
    { "country": "Italy", "capital": "Rome" },
    { "country": "Kosovo", "capital": "Pristina" },
    { "country": "Latvia", "capital": "Riga" },
    { "country": "Liechtenstein", "capital": "Vaduz" },
    { "country": "Lithuania", "capital": "Vilnius" },
    { "country": "Luxembourg", "capital": "Luxembourg" },
    { "country": "Malta", "capital": "Valletta" },
    { "country": "Moldova", "capital": "Chișinău" },
    { "country": "Monaco", "capital": "Monaco" },
    { "country": "Montenegro", "capital": "Podgorica" },
    { "country": "Netherlands", "capital": "Amsterdam" },
    { "country": "North Macedonia", "capital": "Skopje" },
    { "country": "Norway", "capital": "Oslo" },
    { "country": "Poland", "capital": "Warsaw" },
    { "country": "Portugal", "capital": "Lisbon" },
    { "country": "Romania", "capital": "Bucharest" },
    { "country": "San Marino", "capital": "San Marino" },
    { "country": "Serbia", "capital": "Belgrade" },
    { "country": "Slovakia", "capital": "Bratislava" },
    { "country": "Slovenia", "capital": "Ljubljana" },
    { "country": "Spain", "capital": "Madrid" },
    { "country": "Sweden", "capital": "Stockholm" },
    { "country": "Switzerland", "capital": "Bern" },
    { "country": "Ukraine", "capital": "Kyiv" },
    { "country": "United Kingdom", "capital": "London" },
    { "country": "Vatican City", "capital": "Vatican City" }
  ],
  "north_america": [
    { "country": "Antigua and Barbuda", "capital": "St. John's" },
    { "country": "Bahamas", "capital": "Nassau" },
    { "country": "Barbados", "capital": "Bridgetown" },
    { "country": "Belize", "capital": "Belmopan" },
    { "country": "Canada", "capital": "Ottawa" },
    { "country": "Costa Rica", "capital": "San José" },
    { "country": "Cuba", "capital": "Havana" },
    { "country": "Dominica", "capital": "Roseau" },
    { "country": "Dominican Republic", "capital": "Santo Domingo" },
    { "country": "El Salvador", "capital": "San Salvador" },
    { "country": "Grenada", "capital": "St. George's" },
    { "country": "Guatemala", "capital": "Guatemala City" },
    { "country": "Haiti", "capital": "Port-au-Prince" },
    { "country": "Honduras", "capital": "Tegucigalpa" },
    { "country": "Jamaica", "capital": "Kingston" },
    { "country": "Mexico", "capital": "Mexico City" },
    { "country": "Nicaragua", "capital": "Managua" },
    { "country": "Panama", "capital": "Panama City" },
    { "country": "Saint Kitts and Nevis", "capital": "Basseterre" },
    { "country": "Saint Lucia", "capital": "Castries" },
    { "country": "Saint Vincent and the Grenadines", "capital": "Kingstown" },
    { "country": "Trinidad and Tobago", "capital": "Port of Spain" },
    { "country": "United States", "capital": "Washington, D.C." }
  ],
  "south_america": [
    { "country": "Argentina", "capital": "Buenos Aires" },
    { "country": "Bolivia", "capital": "Sucre" },
    { "country": "Brazil", "capital": "Brasília" },
    { "country": "Chile", "capital": "Santiago" },
    { "country": "Colombia", "capital": "Bogotá" },
    { "country": "Ecuador", "capital": "Quito" },
    { "country": "French Guiana", "capital": "Cayenne" },
    { "country": "Guyana", "capital": "Georgetown" },
    { "country": "Paraguay", "capital": "Asunción" },
    { "country": "Peru", "capital": "Lima" },
    { "country": "Suriname", "capital": "Paramaribo" },
    { "country": "Uruguay", "capital": "Montevideo" },
    { "country": "Venezuela", "capital": "Caracas" }
  ]
}