// Flash card data - easily configurable
const flashCardSets = {
    geography: [
        { question: "What is the capital of France?", answer: "Paris" },
        { question: "Which country is known as the Land of the Rising Sun?", answer: "Japan" },
        { question: "What is the largest continent?", answer: "Asia" },
        { question: "Which river is the longest in the world?", answer: "The Nile River" },
        { question: "What is the smallest country in the world?", answer: "Vatican City" },
        { question: "Which mountain range contains Mount Everest?", answer: "The Himalayas" },
        { question: "What is the capital of Australia?", answer: "Canberra" },
        { question: "Which desert is the largest hot desert?", answer: "The Sahara Desert" },
        { question: "What is the capital of Brazil?", answer: "Brasília" },
        { question: "Which country has the most natural lakes?", answer: "Canada" },
        { question: "What is the longest river in Europe?", answer: "The Volga River" },
        { question: "Which city is known as the Big Apple?", answer: "New York City" },
        { question: "What is the capital of Egypt?", answer: "Cairo" },
        { question: "Which ocean is the largest?", answer: "Pacific Ocean" },
        { question: "What is the highest waterfall in the world?", answer: "Angel Falls" },
        { question: "Which country is shaped like a boot?", answer: "Italy" },
        { question: "What is the capital of Canada?", answer: "Ottawa" },
        { question: "Which sea is the saltiest?", answer: "The Dead Sea" },
        { question: "What is the southernmost continent?", answer: "Antarctica" },
        { question: "Which country has the most time zones?", answer: "France" }
    ],
    math: [
        { question: "What is 7 × 8?", answer: "56" },
        { question: "What is 144 ÷ 12?", answer: "12" },
        { question: "What is 15 + 27?", answer: "42" },
        { question: "What is 100 - 37?", answer: "63" },
        { question: "What is 9²?", answer: "81" },
        { question: "What is √64?", answer: "8" },
        { question: "What is 25% of 80?", answer: "20" },
        { question: "What is 12 × 15?", answer: "180" },
        { question: "What is 200 ÷ 8?", answer: "25" },
        { question: "What is 45 + 67?", answer: "112" },
        { question: "What is 150 - 89?", answer: "61" },
        { question: "What is 6³?", answer: "216" },
        { question: "What is √121?", answer: "11" },
        { question: "What is 30% of 150?", answer: "45" },
        { question: "What is 11 × 11?", answer: "121" },
        { question: "What is 360 ÷ 15?", answer: "24" },
        { question: "What is 78 + 95?", answer: "173" },
        { question: "What is 300 - 147?", answer: "153" },
        { question: "What is 4⁴?", answer: "256" },
        { question: "What is √196?", answer: "14" }
    ],
    science: [
        { question: "What is the chemical symbol for water?", answer: "H₂O" },
        { question: "How many bones are in an adult human body?", answer: "206" },
        { question: "What is the fastest land animal?", answer: "Cheetah" },
        { question: "What gas do plants absorb during photosynthesis?", answer: "Carbon Dioxide" },
        { question: "What is the hardest natural substance?", answer: "Diamond" },
        { question: "How many chambers does a human heart have?", answer: "4" },
        { question: "What is the largest planet in our solar system?", answer: "Jupiter" },
        { question: "What is the chemical symbol for gold?", answer: "Au" },
        { question: "What type of animal is a dolphin?", answer: "Mammal" },
        { question: "What is the speed of light?", answer: "299,792,458 m/s" },
        { question: "What is the most abundant gas in Earth's atmosphere?", answer: "Nitrogen" },
        { question: "How many teeth does an adult human typically have?", answer: "32" },
        { question: "What is the smallest unit of matter?", answer: "Atom" },
        { question: "Which blood type is the universal donor?", answer: "O negative" },
        { question: "What is the hottest planet in our solar system?", answer: "Venus" },
        { question: "How many pairs of chromosomes do humans have?", answer: "23" },
        { question: "What is the chemical formula for salt?", answer: "NaCl" },
        { question: "What is the largest organ in the human body?", answer: "Skin" },
        { question: "How long does it take for Earth to orbit the Sun?", answer: "365.25 days" },
        { question: "What is the study of earthquakes called?", answer: "Seismology" }
    ],
    history: [
        { question: "In which year did World War II end?", answer: "1945" },
        { question: "Who was the first person to walk on the moon?", answer: "Neil Armstrong" },
        { question: "Which empire was ruled by Julius Caesar?", answer: "Roman Empire" },
        { question: "In which year did the Berlin Wall fall?", answer: "1989" },
        { question: "Who painted the Mona Lisa?", answer: "Leonardo da Vinci" },
        { question: "Which country gifted the Statue of Liberty to the USA?", answer: "France" },
        { question: "In which year did the Titanic sink?", answer: "1912" },
        { question: "Who was the first President of the United States?", answer: "George Washington" },
        { question: "Which ancient wonder was located in Alexandria?", answer: "The Lighthouse of Alexandria" },
        { question: "In which year did World War I begin?", answer: "1914" },
        { question: "Who wrote 'Romeo and Juliet'?", answer: "William Shakespeare" },
        { question: "Which civilization built Machu Picchu?", answer: "The Incas" },
        { question: "In which year did the American Civil War end?", answer: "1865" },
        { question: "Who was known as the Iron Lady?", answer: "Margaret Thatcher" },
        { question: "Which explorer discovered America in 1492?", answer: "Christopher Columbus" },
        { question: "In which city was John F. Kennedy assassinated?", answer: "Dallas" },
        { question: "Who was the last Pharaoh of Egypt?", answer: "Cleopatra VII" },
        { question: "Which war was fought from 1950-1953?", answer: "Korean War" },
        { question: "Who invented the printing press?", answer: "Johannes Gutenberg" },
        { question: "In which year did the Soviet Union collapse?", answer: "1991" }
    ]
};